### ISSUE TITLE
開催日決める

### ISSUE THREAD

**Issue by rosylilly** [java-ja/java-ja.OSS#2]
直近で開催されるでかいイベントを避けつつなるはや開催を目指す(鉄は熱いうちに打て)。

**Comment by rosylilly** [comment]
10月中頃開催なつもりで。

ちなみにかぶりたくなさそうなヤツは
- 10/10 PyCon
- 10/15 JAWS-UG ARCH
- 10/15 ログ分析 vol.1

ぐらいがぱっとみで見つかったので、
- 10/16 
- 10/23

ぐらいの気持ちでいるといいかなぁ。まだわかんね。

**Comment by kwappa** [comment]
会場、10/16, 23ともにNGだ…。意外と埋まっておる。

10/5(月)、10/6(火)、10/14(水)、10/19(月)、10/26〜30あたりが空き。

**Comment by rosylilly** [comment]
10/31 の ISUCON は絶対避けたいので 14 の水狙いいいかもな

**Comment by kwappa** [comment]
5,6,14,19仮押さえした

**Comment by rosylilly** [comment]
@kwappa 愛してる

**Comment by yoshiori** [comment]
@twada ping

**Comment by mizzy** [comment]
10月は26日の週はどうなるかわからないので、外してもらえると助かります！あと、火曜もできれば外してもらえるとありがたいですが、会場の都合や他の登壇者の方の都合で火曜が良い、ということであれば、調整できます！

**Comment by yoshiori** [comment]
> その三人に 40 分位の発表お願い + いつものごとくツッコミあり
> にしたら 60分 \* 3 位になるんじゃないかな。
> で、3 時間なので 19:30 からはじめて 22:30 、ちょっと伸びて 23 時とかで

な感じで発表をお願いしたいです！

**Comment by tagomoris** [comment]
10/14 の日中はデブサミ秋とかいうイベントの基調講演に呼ばれてるのと、10/15朝の成田便でヨーロッパ行くので、二重の意味で当日夜はきびしいです。というかちょっと無理。
http://event.shoeisha.jp/devsumi/20151014/
10/20早朝に帰国なので10/19も不可能です。
候補にあるうちだと 10/5, 6 だと都合がいいです。10/26〜30 はISUCON準備があるので可能な限り避けたい。

**Comment by kwappa** [comment]
火曜外すと10/5(月)なら、という感じ！ @twada さーん！

**Comment by twada** [comment]
10/5 空いています!
(10/6 空いてません)

**Comment by kwappa** [comment]
fixed!!!

**Comment by mizzy** [comment]
承知！

**Comment by rosylilly** [comment]
ｲｪｴｴｴｴｴｴｴｴｱｱｱｱｱｱｱｱｱｱｱｱｱ(5日で)

**Comment by yoshiori** [comment]
おっっっｋ

**Comment by tagomoris** [comment]
いぇあ
