### ISSUE TITLE
登壇者決定

### ISSUE THREAD

**Issue by rosylilly** [java-ja/java-ja.OSS#3]
オファーする人
- [x] tagomoris
- [x] t_wada
- [x] mizzy

他呼びたい人がいればコメントすること

**Comment by yoshiori** [comment]
その三人に 40 分位の発表お願い + いつものごとくツッコミあり

にしたら 60分 \* 3 位になるんじゃないかな。
で、3 時間なので 19:30 からはじめて 22:30 、ちょっと伸びて 23 時とかで

**Comment by rosylilly** [comment]
よさそう。パネルするのも考えてたけど厳しそうだな。

**Comment by mizzy** [comment]
10月は26日の週はどうなるかわからないので、外してもらえると助かります！あと、火曜もできれば外してもらえるとありがたいですが、会場の都合や他の登壇者の方の都合で火曜が良い、ということであれば、調整できます！

**Comment by yoshiori** [comment]
皆様が快く引き受けてくれたので done

**Comment by yoshiori** [comment]
日程はコチラで詰めましょう https://github.com/java-ja/java-ja.OSS/issues/2
