### ISSUE TITLE
一般参加募集開始

### ISSUE THREAD

**Issue by rosylilly** [java-ja/java-ja.OSS#4]
compass あたりで適当にイベント作る。

このイベントサービス使え！ってのがなければ compass 使うぞ俺は。

**Comment by kwappa** [comment]
connpass :+1:

**Comment by rokujyouhitoma** [comment]
:+1:

**Comment by rosylilly** [comment]
キャパ90で connpass 出します。

**Comment by rosylilly** [comment]
開始済み http://connpass.com/event/19690/
