### ISSUE TITLE
飯、酒の手配

### ISSUE THREAD

**Issue by rosylilly** [java-ja/java-ja.OSS#5]
参加人数決めてから手配開始するので当分先でよし

**Comment by rosylilly** [comment]
会場決まったら飲食可能かの確認必須

**Comment by rosylilly** [comment]
ドワンゴなら飲食可とのこと

**Comment by kwappa** [comment]
:beer:  カクヤスと :pizza: ストロベリーコーンズは実績あり。 :sushi: は知らぬが、銀のさらならなんとかしてくれるだろう :money_with_wings:

**Comment by rosylilly** [comment]
カクヤスでビール4ケースくらい買いたい

**Comment by tagomoris** [comment]
スーパードライだったら暴れます

**Comment by yoshiori** [comment]
@kwappa 任せでいい？

**Comment by kwappa** [comment]
:ok_woman:

**Comment by taichi** [comment]
コカ・コーラ入れて下さい

**Comment by kwappa** [comment]
# 酒の見積もり

90定員、歩留まり70、飲酒率70%、平均350mlを2本と仮定。
- アルコール
  - `70 * 0.7 * 2 = 98`
  - 24本 \* 4ケース = 96本
- ソフトドリンク
  - `70 * 0.3 * 2 *0.35 = 14.7 (リットル)`
  - (コーラ3本 + お茶3本 + ジュース2本) \* 2 = 16（リットル）

**Comment by kwappa** [comment]
19405JPY(だいたい :point_up: の見積もりどおり)

**Comment by kwappa** [comment]
19時〜20時、冷えたのを手配done

**Comment by kwappa** [comment]
76272JPY pizza(サルヴァトーレ・クオモでLサイズ32枚)

**Comment by kwappa** [comment]
あれーなんか安いぞ？
不健康神社からお菓子仕入れつつ、スピーカー用ビールは別途コンビニ仕入れしときます。

**Comment by kwappa** [comment]
黒ラベルとプレモル、缶チューハイ各種にしました。コンビニ仕入れはヱビスにしとこう。

**Comment by kwappa** [comment]
50人以上支払いがあれば回せそう。よしよし。
