### ISSUE TITLE
ドワンゴ社内向け生放送したい

### ISSUE THREAD

**Issue by kwappa** [java-ja/java-ja.OSS#7]
ドワンゴ社内環境で、社内エンジニア向けに生放送したいです。
- ドワンゴ社員しか見えません
- ドワンゴ社員からのコメント流れます
- タイムシフトは残りません

ご承諾いただける方はチェックをお願いします
- [x] @twada
- [x] @tagomoris
- [x] @mizzy

**Comment by mizzy** [comment]
チェック入れようと思ったけど、権限ないみたいで入れられないみたいですね。
生放送OKです！

**Comment by twada** [comment]
本当だチェック付けられないですね。
放送 OK です。

**Comment by kwappa** [comment]
なんと、チェック押せないですか :bow:

**Comment by tagomoris** [comment]
押せないですね。OKです。
ところでドワンゴ社内に限定するのは何か理由が？

**Comment by kwappa** [comment]
> ドワンゴ社内に限定するのは何か理由が？

直前まで社内エンジニアのLTイベントを社内向けに放送してるので、放送機材がそのまま使える、という理由です。

よく考えたらjava-jaコミュあったな。社外に向けてやる、になってもいいですか？

**Comment by mizzy** [comment]
社外でもOKです。

**Comment by tagomoris** [comment]
OK > 社外

**Comment by twada** [comment]
社外 OK です

**Comment by kwappa** [comment]
:pray:

**Comment by yoshiori** [comment]
そう言えば運コメのプロがいた

**Comment by rosylilly** [comment]
生放送とかよくわかんないんでおまかせしますね
